FROM traefik:2.10
ARG PROXY_DOMAIN_NAME="localtest.me"

ENV PROXY_DOMAIN_NAME ${PROXY_DOMAIN_NAME}

# Configure the entrypoints we want to expose
ENV TRAEFIK_ENTRYPOINTS_WEB_ADDRESS ${TRAEFIK_ENTRYPOINTS_WEB_ADDRESS:-:80}
ENV TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS ${TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS:-:443}

ENV TRAEFIK_ENTRYPOINTS_NEO4J_ADDRESS ${TRAEFIK_ENTRYPOINTS_NEO4J_ADDRESS:-:7687}
ENV TRAEFIK_ENTRYPOINTS_NEO4J_TRANSPORT_RESPONDINGTIMEOUTS_IDLETIMEOUT=60
ENV TRAEFIK_ENTRYPOINTS_NEO4J_TRANSPORT_RESPONDINGTIMEOUTS_READTIMEOUT=60
ENV TRAEFIK_ENTRYPOINTS_NEO4J_TRANSPORT_RESPONDINGTIMEOUTS_WRITETIMEOUT=60

ENV TRAEFIK_ENTRYPOINTS_MSSQL_ADDRESS ${TRAEFIK_ENTRYPOINTS_MSSQL_ADDRESS:-:1433}
ENV TRAEFIK_ENTRYPOINTS_MSSQL_TRANSPORT_RESPONDINGTIMEOUTS_IDLETIMEOUT=60
ENV TRAEFIK_ENTRYPOINTS_MSSQL_TRANSPORT_RESPONDINGTIMEOUTS_READTIMEOUT=60
ENV TRAEFIK_ENTRYPOINTS_MSSQL_TRANSPORT_RESPONDINGTIMEOUTS_WRITETIMEOUT=60

ENV TRAEFIK_ENTRYPOINTS_POSTGRES_ADDRESS ${TRAEFIK_ENTRYPOINTS_POSTGRES_ADDRESS:-:5432}
ENV TRAEFIK_ENTRYPOINTS_POSTGRES_TRANSPORT_RESPONDINGTIMEOUTS_IDLETIMEOUT=60
ENV TRAEFIK_ENTRYPOINTS_POSTGRES_TRANSPORT_RESPONDINGTIMEOUTS_READTIMEOUT=60
ENV TRAEFIK_ENTRYPOINTS_POSTGRES_TRANSPORT_RESPONDINGTIMEOUTS_WRITETIMEOUT=60

ENV TRAEFIK_ENTRYPOINTS_MYSQL_ADDRESS ${TRAEFIK_ENTRYPOINTS_MYSQL_ADDRESS:-:3306}
ENV TRAEFIK_ENTRYPOINTS_MYSQL_TRANSPORT_RESPONDINGTIMEOUTS_IDLETIMEOUT=60
ENV TRAEFIK_ENTRYPOINTS_MYSQL_TRANSPORT_RESPONDINGTIMEOUTS_READTIMEOUT=60
ENV TRAEFIK_ENTRYPOINTS_MYSQL_TRANSPORT_RESPONDINGTIMEOUTS_WRITETIMEOUT=60

# Configure the re-routing of http to https
ENV TRAEFIK_ENTRYPOINTS_WEB_HTTP_MIDDLEWARES ${TRAEFIK_ENTRYPOINTS_WEB_HTTP_MIDDLEWARES:-redirect-to-https@file}
ENV TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS ${TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS:-true}

# Configure Treafik dashboard and provider settings
ENV TRAEFIK_API_DASHBOARD ${TRAEFIK_API_DASHBOARD:-true}
ENV TRAEFIK_PROVIDERS_DOCKER ${TRAEFIK_PROVIDERS_DOCKER:-true}
ENV TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT ${TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT:-false}
ENV TRAEFIK_PROVIDERS_DOCKER_DEFAULTRULE "Host(`{{ or (index .Labels \"traefik.hostname\") (index .Labels \"com.docker.compose.service\") .Name }}.${PROXY_DOMAIN_NAME}`)"
ENV TRAEFIK_PROVIDERS_DOCKER_ALLOWEMPTYSERVICES ${TRAEFIK_PROVIDERS_DOCKER_ALLOWEMPTYSERVICES:-true}
ENV TRAEFIK_PROVIDERS_DOCKER_NETWORK ${TRAEFIK_PROVIDERS_DOCKER_NETWORK:-proxy}
ENV TRAEFIK_PROVIDERS_FILE_FILENAME ${TRAEFIK_PROVIDERS_FILE_FILENAME:-/etc/traefik/dynamic.yml}
ENV TRAEFIK_LOG_LEVEL ${TRAEFIK_LOG_LEVEL:-DEBUG}
ENV TRAEFIK_SERVERSTRANSPORT_INSECURESKIPVERIFY ${TRAEFIK_SERVERSTRANSPORT_INSECURESKIPVERIFY:-true}

LABEL traefik.enable=true
LABEL traefik.hostname=proxy
LABEL traefik.http.routers.proxy.service=api@internal


COPY ./dynamic.yml /etc/traefik/dynamic.yml
COPY certs/ /etc/traefik/certs/